# Generated by Django 3.1.1 on 2023-10-14 18:32

from django.db import migrations
import users.querysets.anlyses


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='analyses',
            managers=[
                ('objects', users.querysets.anlyses.AnalysesManager()),
            ],
        ),
    ]
